version: "3.9"
services:
  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  rails:
    depends_on:
      - db
    image: clementines-dashboard
    ports:
      - "9001:3000"
    restart: always
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 1
volumes:
  db_data:
